# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-11 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200411_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/%Y/%m/%d'),
        ),
    ]
