# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200413_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d'),
        ),
    ]
