# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200413_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
