# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20200414_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
