# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20200414_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d'),
        ),
    ]
