# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20200414_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
