language: python
python:
  - "3.8"
# command to install dependencies
install:
  - "pip3 install -r requirements.txt"
# command to run tests
script:
  - SECRET_KEY="whatever" python manage.py test