# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.TextField(),
        ),
    ]
