# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-30 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBid',
            new_name='ProductBid',
        ),
    ]
