# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-06 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200406_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
