# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_bid_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
