# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200329_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M %p'),
        ),
    ]
