# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200407_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
